.outerspatial-symbol-library-icon {
  background-image: url(images/outerspatial-symbol-library-sprite.png);
  background-position: 24px 24px;
  background-repeat: no-repeat;
  height: 24px;
  overflow: hidden;
  text-indent: -9999px;
  width: 24px;
}
.title-box .outerspatial-symbol-library-icon.full {
  display: block;
  left: 0;
  margin: auto;
  right: 0;
  width: 54px;
}
@media
  only screen and (-webkit-min-device-pixel-ratio: 2),
  only screen and (min-device-pixel-ratio: 2) {
    .maki-icon {
      background-image: url(images/outerspatial-symbol-library-sprite@2x.png);
      background-size: 000px 000px; /* Replaced automatically by render.sh */
    }
  }
}

/* individual background-positions auto-generated by render.sh: */
